import type { Express } from "express";
import { registerCapabilitiesRoutes } from "./capabilities.js";
import { registerModelsRoutes } from "./models.js";
import { registerEventsRoute } from "./events.js";
import { registerHealthRoutes } from "./health.js";
import { registerAdminRoutes } from "./admin.js";
import { registerHistoryRoutes } from "./history.js";
import { registerAssetsRoutes } from "./assets.js";
import { registerSpriteRecipeRoutes } from "./spriteRecipes.js";
import { registerSpriteGenerationRoutes } from "./spriteGeneration.js";
import { registerSpriteAtlasRoutes } from "./spriteAtlas.js";
import { registerAssetDerivedRoutes } from "./assetDerived.js";
import { registerVideoKeyingRoutes } from "./videoKeying.js";
import { registerSessionRoutes } from "./sessions.js";
import { registerEditRoutes } from "./edit.js";
import { registerMediaMergeRoutes } from "./mediaMerge.js";
import { registerNodeRoutes } from "./nodes.js";
import { registerNodeRefRoutes } from "./nodeRefs.js";
import { registerNodeTemplateRoutes } from "./nodeTemplates.js";
import { registerGenerateRoutes } from "./generate.js";
import { registerMultimodeRoutes } from "./multimode.js";
import { registerStorageRoutes } from "./storage.js";
import { registerCardNewsRoutes } from "./cardNews.js";
import { registerMetadataRoutes } from "./metadata.js";
import { registerPromptRoutes } from "./prompts.js";
import { registerPromptImportRoutes } from "./promptImport.js";
import { registerAnnotationRoutes } from "./annotations.js";
import { registerCanvasVersionRoutes } from "./canvasVersions.js";
import { registerComfyRoutes } from "./comfy.js";
import { registerImageImportRoutes } from "./imageImport.js";
import { registerPromptBuilderRoutes } from "./promptBuilder.js";
import { registerAgentRoutes } from "./agent.js";
import { registerGrokRoutes } from "./grok.js";
import { registerAgyRoutes } from "./agy.js";
import { registerVideoRoutes } from "./video.js";
import { registerWorkflowRoutes } from "./workflow.js";
import { registerVideoExtendedRoutes } from "./videoExtended.js";
import { registerQuotaRoutes } from "./quota.js";
import { registerAuthRoutes } from "./auth.js";
import { registerMcpConnectionRoutes } from "./mcpConnections.js";
import { registerMcpMediaRoutes } from "./mcpMedia.js";
import { registerMcpRecoverRoutes } from "./mcpRecover.js";
import { registerMcpTempReferenceRoutes } from "./mcpTempReferences.js";
import { registerMcpMultishotRoutes } from "./mcpMultishot.js";
import { registerContractRoutes } from "./contracts.js";
import { mountKeyRoutes } from "./keys.js";
import { registerGenerationRequestLogRoutes } from "./generationRequestLog.js";
import { type RouteRuntimeContext, requireRuntimeContext } from "../lib/runtimeContext.js";

export function configureRoutes(app: Express, ctxRaw: RouteRuntimeContext) {
  const ctx = requireRuntimeContext(ctxRaw);
  registerEventsRoute(app, ctx);
  registerHealthRoutes(app, ctx);
  registerAdminRoutes(app, ctx);
  registerCapabilitiesRoutes(app, ctx);
  registerStorageRoutes(app, ctx);
  registerMetadataRoutes(app, ctx);
  registerHistoryRoutes(app, ctx);
  registerAssetsRoutes(app, ctx);
  registerSpriteRecipeRoutes(app);
  registerSpriteGenerationRoutes(app, ctx);
  registerSpriteAtlasRoutes(app, ctx);
  registerAssetDerivedRoutes(app, ctx);
  registerVideoKeyingRoutes(app, ctx);
  registerAnnotationRoutes(app, ctx);
  registerCanvasVersionRoutes(app, ctx);
  registerImageImportRoutes(app, ctx);
  registerComfyRoutes(app, ctx);
  registerSessionRoutes(app, ctx);
  registerEditRoutes(app, ctx);
  registerNodeRoutes(app, ctx);
  registerMediaMergeRoutes(app, ctx);
  registerWorkflowRoutes(app, ctx);
  registerNodeRefRoutes(app, ctx);
  registerNodeTemplateRoutes(app);
  if (ctx.config.features.cardNews) registerCardNewsRoutes(app, ctx);
  registerMultimodeRoutes(app, ctx);
  registerGenerateRoutes(app, ctx);
  registerAgentRoutes(app, ctx);
  registerPromptBuilderRoutes(app, ctx);
  registerPromptRoutes(app, ctx);
  registerPromptImportRoutes(app, ctx);
  registerGrokRoutes(app, ctx);
  registerAgyRoutes(app);
  registerVideoRoutes(app, ctx);
  registerVideoExtendedRoutes(app, ctx);
  registerQuotaRoutes(app, ctx);
  registerAuthRoutes(app, ctx);
  registerMcpConnectionRoutes(app, ctx);
  registerModelsRoutes(app, ctx);
  registerMcpMediaRoutes(app, ctx);
  registerMcpRecoverRoutes(app, ctx);
  registerMcpTempReferenceRoutes(app, ctx);
  registerMcpMultishotRoutes(app, ctx);
  registerContractRoutes(app, ctx);
  mountKeyRoutes(app, ctx);
  registerGenerationRequestLogRoutes(app, ctx);
}
